### ISSUE TITLE
cache not working

### ISSUE THREAD

**Issue by mrsoto** [flightphp/core#219] opened 2015-11-16 02:37 UTC
Hello,
   I'm trying to use cache functionality but Flight::json($data); always produce non cache-able response. It doesn't matter if I do call any or all of:

```
Flight::etag($tag)
Flight::lastmodified($lastModify) 
Flight::response()->cache(time() + $hours * 60 * 60);
$rows = NewsFacade::query($page, $pageSize);
Flight::json($rows);
```

I do stop in json and response' headers is empty

the response is something like

```
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:Keep-Alive
Content-Length:1321
Content-Type:application/json
Date:Mon, 16 Nov 2015 02:21:52 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive:timeout=5, max=100
Pragma:no-cache
```

**Comment by mikecao** [comment] 2015-12-04 12:44
I think the issue is with the `json` method always sending a new response so the headers are lost. I'll need to change how Flight sends responses for certain methods.

**Comment by mrsoto** [comment] 2015-12-06 04:14
This has a huge impact in an application which is AngularJS/PHP using CORS. Always request OPTIONS doubling requests.

**Comment by mikecao** [comment] 2015-12-09 09:10
Fixed in commit b9dfda3fd692421832b650744343b4fce6fe27d6.

**Comment by mrsoto** [comment] 2015-12-09 23:25
Great.
Are you planning to publish 1.2.14 in composer repo?

Thanks for this software!

**Comment by emanwebdev** [comment] 2015-12-14 11:02
gosh...  for the people relying on it so far !!!!

what's hapopening in background??

**Closed as completed** 2015-12-18 06:28 UTC
Labels: Bug
